LF-10275: Fix error: ‘uint32_t’ does not name a type
There'll be build error when using GCC 13:

In file included from SignalProcessor_VoiceSeekerLight.h:13,
                 from SignalProcessor_VoiceSeekerLight.cpp:11:
SignalProcessorImplementation.h:100:21: error: ‘uint32_t’ does not name a type
  100 |             virtual uint32_t
      |                     ^~~~~~~~

GCC 13 has changes in header dependency. <cstdint> should be included
explicitly.

Signed-off-by: Chancel Liu <chancel.liu@nxp.com>